definitions:
  ping.PingResponse:
    properties:
      alive:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.PingResponse'
      summary: ping server
      tags:
      - ping
swagger: "2.0"
